coverb(fight, fight).
coverb(live, life).
coverb(dance, dance).
coverb(smile, smile).
coverb(laugh, laugh).
coverb(dream, dream).
coverb(walk, walk).
coverb(die, death).
coverb(sleep, sleep).
coverb(grow, growth).
coverb(talk, talk).
coverb(sing, song).
coverb(think, thought).
coverb(yawn, yawn).
coverb(boogie, boogie).
coverb(waltz, waltz).
coverb(talk, talk).
coverb(drop, drop).
coverb(fall, fall).
coverb(run, run).
coverb(sneeze, sneeze).
coverb(grin, grin).
coverb(bounce, bounce).
coverb(sigh, sigh).
coverb(wink, wink).
